const mongoose = require('mongoose');

const Schema = mongoose.Schema,
    ObjectId = Schema.ObjectId;
const orderSchema = mongoose.Schema({
    userId:{
        type:ObjectId,
        required:true
    },
    orderId:{
        type:String,
        required:true
    },
    deliveryAddress:[
        {
            fullName:{
                type:String,
                required:true
            },
            mobileNumber:{
                type:String,
                required:true
            },
            Pincode:String,
            locality:String,
            address:{
                type:String,
                required:true
            },
            district:String,
            state:String
        }
    ],
    orderItems:[
        {
            productId:{
                type:ObjectId,
                required:true
            },
            productQuantity:{
                type:Number,
                required:true
            },
            productPrice:{
                type:Number,
                required:true
            },
        }
    ],
    totalAmount:{
        type:Number,
        required:true
    },
    deliveryDate:{
        type:Date,
        required:true
    },
    orderDate:{
        type:Date,
        default:Date.now(),
        required:true
    },
    paymentType:{
        type:String,
        required:true
    },
    orderStatus:{
        type:String,
        required:true
    },
    paymentId:String,
    cartId:String,
    deliveryCharge:{
        type:Number,
        default:0,
        required:true
    },
    discount:{
        type:Number,
        default:0,
        required:true
    },
    orderNote:String,
    delFlag:{
        type:Number,
        default:0,
        required:true
    }
});
module.exports = mongoose.model(process.env.ORDER_COLLECTION,orderSchema);